#include "music.h"


// Array of Music objects
static const Music musics[TOTAL_MUSICS] = {
  { A01_FRENTE_AO_SOL,
    "Montgomery",
    "Frente Ao Sol",
    "F#",
    113,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 0 },
      { CH_FLUIDSYNTH, CC, 0, 0 },
      { CH_FLUIDSYNTH, PC, 0, 0 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 0 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 0 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 0 } },
    { "",
      "c# d e f#" } },
  { A02_FUGAS_E_LAMENTOS,
    "Montgomery",
    "Fugas e Lamentos",
    "C",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 1 },
      { CH_FLUIDSYNTH, CC, 0, 1 },
      { CH_FLUIDSYNTH, PC, 0, 0 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 1 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 1 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 1 } },
    { "I,V: Em Am D Em",
      "C: Em C Em D",
      "B: C Am C G",
      "Solo:",
      "b a g f# e d f#" } },
  { A03_FINAL_DE_TEMPESTADE,
    "Montgomery",
    "Final de Tempestade",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 2 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 2 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 2 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 2 } } },
  { A04_ESTRADA_DE_SONHOS,
    "Montgomery",
    "Estrada de Sonhos",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 3 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 3 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 3 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 3 } } },
  { A05_ALGUM_LUGAR,
    "Montgomery",
    "Algum Lugar",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 4 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 4 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 4 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 4 } } },
  { A06_PINTURA,
    "Montgomery",
    "Pintura",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 5 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 5 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 5 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 5 } } },
  { A07_A_MESMA_POESIA,
    "Montgomery",
    "A mesma poesia",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 6 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 6 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 6 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 6 } } },
  { A08_PINOQUIO,
    "Montgomery",
    "Pinoquio",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 7 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 7 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 7 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 7 } } },
  { A09_ATE_O_SOL_NASCER,
    "Montgomery",
    "Até o sol nascer",
    "C#",
    174,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 8 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 8 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 8 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 8 } } },
  { A10_BEIJOS_DE_ARAME_FARPADO,
    "Montgomery",
    "Beijos de Arame Farpado",
    "B",
    99,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 9 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 9 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 9 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 9 } } },
  { A11_VIVER_MORRER_E_ESQUECER,
    "Montgomery",
    "Viver Morrer e Esquecer",
    "A",
    144,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 10 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 10 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 10 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 10 } } },
  { A12_ME_ESCOLHA,
    "Montgomery",
    "Me Escolha",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 11 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 11 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 11 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 11 } } },
  { A13_O_PERDAO,
    "Montgomery",
    "O Perdão",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 12 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { A14_CHUVA_INOCENTE,
    "Montgomery",
    "Chuva Inocente",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 13 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 13 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 13 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 13 } } },
  { A15_TODO_TEMPO,
    "Montgomery",
    "Todo Tempo",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 14 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 14 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 14 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 14 } } },
  { A16_EXODO,
    "Montgomery",
    "Êxodo",
    "",
    0,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 0 },
      { CH_NORD_LEAD, PC, 0, 15 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 15 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 15 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 15 } } },

  // Cover Songs

  {
    B02_MYSTERIOUS_WAYS,
    "U2",
    "Mysterious Ways",
    "G",
    99,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 1 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 1 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 1 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 1 } },
    { "V: g c g d",
      "PC: G C",
      "C: G C A# F",
      "O: D ... Gm C Gm F" } },
  { B03_IVE_BEEN_LOSING_YOU,
    "A-ha",
    "I've been losing you",
    "C",
    118,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 2 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 2 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 2 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 2 } } },
  { B05_SAVE_A_PRAYER,
    "Duran Duran",
    "Save a Prayer",
    "",
    113,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 4 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 4 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 4 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 4 } } },
  { B06_WICKED_GAME,
    "Chris Isaac",
    "Wicked Game",
    "B",
    79,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 5 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 5 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 5 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 5 } } },
  { B08_LOVE_WILL_TEAR_US_APART,
    "Joy Division",
    "Love Will Tear Us Apart",
    "",
    148,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 7 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 7 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 7 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 7 } } },
  { B10_BITTER_SWEET_SYMPHONY,
    "The Verve",
    "Bitter Sweet Symphony",
    "",
    86,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 9 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 9 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 9 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 9 } } },
  { B11_CARTA_AOS_MISSIONARIOS,
    "Uns e Outros",
    "Carta aos Missionários",
    "F#",
    76,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 10 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 10 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 10 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 10 } } },
  { B13_INDIOS,
    "Legião Urbana",
    "Indios",
    "",
    112,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 12 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B15_ENJOY_THE_SILENCE,
    "Depeche Mode",
    "Enjoy the Silence",
    "",
    120,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 14 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B17_BACK_ON_THE_CHAIN_GANG,
    "The Pretenders",
    "Back on the chain",
    "",
    153,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 16 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B18_LIPS_LIKE_SUGAR,
    "Echo & The Bunnymen",
    "Lips Like Sugar",
    "",
    126,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 17 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B20_JUST_LIKE_HEAVEN,
    "The Cure",
    "Just Like Heaven",
    "",
    151,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 19 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B22_JUVENILIA,
    "RPM",
    "Juvenilia",
    "G",
    129,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 21 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B24_WHERE_IS_MY_MIND,
    "Pixies",
    "Where is my mind",
    "",
    82,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 23 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B25_MEUS_BONS_AMIGOS,
    "Barão Vermelho",
    "Meus bons Amigos",
    "",
    96,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 24 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B26_CRUSH_WITH_EYELINER,
    "REM",
    "Crush With Eyeliner",
    "",
    126,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 25 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B27_DONT_YOU_FORGET_ABOUT_ME,
    "Simple Minds",
    "Don't you forget about me",
    "",
    112,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 26 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B28_WONDERWALL,
    "Oasis",
    "Wonderwall",
    "",
    87,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 27 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B29_DANIEL_NA_COVA_DOS_LEOES,
    "Legião Urbana",
    "Daniel na cova dos leões",
    "",
    173,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 28 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B30_NEVER_TEAR_US_APART,
    "INXS",
    "Never tear us apart",
    "",
    92,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 29 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B31_BLINDING_LIGHTS,
    "The weeknd",
    "Blinding Lights",
    "",
    171,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 30 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B32_THE_ONE_I_LOVE,
    "REM",
    "The one I love",
    "",
    124,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 31 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B33_WITH_OR_WITHOUT_YOU,
    "U2",
    "With or Without You",
    "",
    110,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 32 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B34_ONE,
    "U2",
    "One",
    "",
    91,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 33 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B35_UNCHAINED_MELODY,
    "U2",
    "Unchained Melody",
    "",
    91,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 34 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B36_THE_END_OF_THE_WORLD,
    "U2",
    "The end of the world",
    "",
    102,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 35 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B37_NEW_YEARS_DAY,
    "U2",
    "New Year's Day",
    "",
    135,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 36 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B38_ATE_QUANDO_ESPERAR,
    "Plebe Rude",
    "Ate quando esperar",
    "",
    94,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 37 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B40_SIDE,
    "Travis",
    "Side",
    "",
    80,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 39 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B41_DANCING_IN_THE_DARK,
    "Bruce Springsteen",
    "Dancing in the dark",
    "",
    149,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 40 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B42_ONLY_HAPPY_WHEN_IT_RAINS,
    "Garbage",
    "Only happy when it",
    "",
    121,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 41 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B43_REPTILIA,
    "Reptilia",
    "The Strokes",
    "",
    158,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 42 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B44_SHE_SELLS_SANCTUARY,
    "The Cult",
    "She sells sanctuar",
    "",
    139,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 43 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B45_ENVELHECO_NA_CIDADE,
    "Ira",
    "Envelheco Na Cidad",
    "",
    117,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 44 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B46_SOMEBODY_TOLD_ME,
    "The Killers",
    "Somebody Told Me",
    "",
    138,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 45 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B47_STOP_CRYING_YOUR_HEART_OUT,
    "Oasis",
    "Stop Crying",
    "",
    150,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 46 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B48_HEROES,
    "David Bowie",
    "Heroes",
    "",
    116,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 47 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B49_TAKE_ME_OUT,
    "Franz Ferdinand",
    "Take Me Out",
    "",
    104,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 48 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } },
  { B50_SUEDEHEAD,
    "Morrissey",
    "Suedehead",
    "D",
    142,
    { { CH_NORD_LEAD, CC, CC_BANK_MSB, 0 },
      { CH_NORD_LEAD, CC, CC_BANK_LSB, 1 },
      { CH_NORD_LEAD, PC, 0, 49 },
      { CH_STRYMON_MOBIUS, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_MOBIUS, CC, 0, 0 },
      { CH_STRYMON_MOBIUS, PC, 0, 12 },
      { CH_STRYMON_TIMELINE, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_TIMELINE, CC, 0, 0 },
      { CH_STRYMON_TIMELINE, PC, 0, 12 },
      { CH_STRYMON_BIGSKY, CC, CC_STRYMON_PATCH_ACTIVE, 0 },
      { CH_STRYMON_BIGSKY, CC, 0, 0 },
      { CH_STRYMON_BIGSKY, PC, 0, 12 } } }
};

static std::unordered_map<String, int> musicMap;
static bool mapInitialized = false;

void initMusicMap() {
  if (mapInitialized) {
    return;
  }

  for (int i = 0; i < TOTAL_MUSICS; i++) {
    String code = String(musics[i].code);
    musicMap[code] = i;
  }

  mapInitialized = true;
}

Music getMusic(int musicIndex) {
  if (musicIndex >= 0 && musicIndex < TOTAL_MUSICS) {
    return musics[musicIndex];
  }

  return musics[0];
}

Music getMusic(const String& key) {
  if (!mapInitialized) {
    initMusicMap();
  }

  if (musicMap.find(key) != musicMap.end()) {
    int index = musicMap[key];
    return musics[index];
  }

  return musics[0];
}
