#include "music.h"

// Array of Music objects
static const Music musics[TOTAL_MUSICS] = {
  { "A01",
    "Montgomery",
    "Frente Ao Sol",
    "C#",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 0 } },
    { "",
      "c# d e f#" } },
  { "A02",
    "Montgomery",
    "Fugas e Lamentos",
    "C",
    100,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 1 } },
    { "I,V: Em Am D Em" ,
      "C: Em C Em D",
      "B: C Am C G",
      "Solo:",
      "b a g f# e d f#"
    } },
  { "A03",
    "Montgomery",
    "Final de Tempestade",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 2 } } },
  { "A04",
    "Montgomery",
    "Estrada de Sonhos",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 3 } } },
  { "A05",
    "Montgomery",
    "Algum Lugar",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 4 } } },
  { "A06",
    "Montgomery",
    "Pintura",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 5 } } },
  { "A07",
    "Montgomery",
    "A mesma poesia",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 6 } } },
  { "A08",
    "Montgomery",
    "Pinoquio",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 7 } } },
  { "A09",
    "Montgomery",
    "Até o sol nascer",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 8 } } },
  { "A10",
    "Montgomery",
    "Beijos de Arame Farpado",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 9 } } },
  { "A11",
    "Montgomery",
    "Viver Morrer e Esquecer",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 10 } } },
  { "A12",
    "Montgomery",
    "Me Escolha",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 11 } } },
  { "A13",
    "Montgomery",
    "O Perdão",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 12 } } },
  { "A14",
    "Montgomery",
    "Chuva Inocente",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 13 } } },
  { "A15",
    "Montgomery",
    "Todo Tempo",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 14 } } },
  { "A16",
    "Montgomery",
    "Êxodo",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 0 },
      { CH_NORD_LEAD, PC, 0, 15 } } },

  // Cover Songs

  {
    "B02",
    "U2",
    "Mysterious Ways",
    "G",
    100,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 1 } },
    { "V: g c g d",
      "PC: G C",
      "C: G C A# F",
      "O: D ... Gm C Gm F" } },
  { "B03",
    "A-ha",
    "I've been losing you",
    "C",
    100,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 2 } } },
  { "B05",
    "Duran Duran",
    "Save a Prayer",
    "",
    113,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 4 } } },
  { "B06",
    "Chris Isaac",
    "Wicked Game",
    "B",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 5 } } },
  { "B08",
    "Joy Division",
    "Love Will Tear Us Apart",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 7 } } },
  { "B10",
    "The Verve",
    "Bitter Sweet Symphony",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 9 } } },
  { "B11",
    "Uns e Outros",
    "Carta aos Missionários",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 10 } } },
  { "B13",
    "Legião Urbana",
    "Indios",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 12 } } },
  { "B15",
    "Depeche Mode",
    "Enjoy the Silence",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 14 } } },
  { "B18",
    "Echo & The Bunnymen",
    "Lips Like Sugar",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 17 } } },
  { "B20",
    "The Cure",
    "Just Like Heaven",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 19 } } },
  { "B22",
    "RPM",
    "Juvenilia",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 21 } } },
  { "B24",
    "Pixies",
    "Where is my mind",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 23 } } },
  { "B25",
    "Barão Vermelho",
    "Meus bons Amigos",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 24 } } },
  { "B26",
    "REM",
    "Crush With Eyeliner",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 25 } } },
  { "B27",
    "Simple Minds",
    "Don't you forget about me",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 26 } } },
  { "B28",
    "Oasis",
    "Wonderwall",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 27 } } },
  { "B29",
    "Legião Urbana",
    "Daniel na cova dos leões",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 28 } } },
  { "B30",
    "INXS",
    "Never tear us apart",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 29 } } },
  { "B31",
    "The weeknd",
    "Blinding Lights",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 30 } } },
  { "B32",
    "REM",
    "The one I love",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 31 } } },
  { "B33",
    "U2",
    "With or Without You",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 32 } } },
  { "B34",
    "U2",
    "One",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 33 } } },
  { "B35",
    "U2",
    "New Year's Day",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 34 } } },
  { "B36",
    "U2",
    "The end of the world",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 35 } } },
  { "B37",
    "U2",
    "New Year's Day",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 36 } } },
  { "B38",
    "Plebe Rude",
    "Ate quando esperar",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 37 } } },
  { "B40",
    "Travis",
    "Side",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 39 } } },
  { "B41",
    "Bruce Springsteen",
    "Dancing in the dar",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 40 } } },
  { "B42",
    "Garbage",
    "Only happy when it",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 41 } } },
  { "B43",
    "U2",
    "With or Without Yu",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 42 } } },
  { "B44",
    "The Cult",
    "She sells sanctuar",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 43 } } },
  { "B45",
    "Ira",
    "Envelheco Na Cidad",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 44 } } },
  { "B46",
    "The Killers",
    "Somebody Told Me",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 45 } } },
  { "B47",
    "Oasis",
    "Stop Crying",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 46 } } },
  { "B48",
    "David Bowie",
    "Heroes",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 47 } } },
  { "B49",
    "Franz Ferdinand",
    "Take Me Out",
    "",
    0,
    { { CH_NORD_LEAD, CC, 0, 0 },
      { CH_NORD_LEAD, CC, 32, 1 },
      { CH_NORD_LEAD, PC, 0, 48 } } }
};

static std::unordered_map<String, int> musicMap;
static bool mapInitialized = false;

void initMusicMap() {
  if (mapInitialized) {
    return;
  }

  for (int i = 0; i < TOTAL_MUSICS; i++) {
    String code = String(musics[i].code);
    musicMap[code] = i;
  }

  mapInitialized = true;
}

Music getMusic(int musicIndex) {
  if (musicIndex >= 0 && musicIndex < TOTAL_MUSICS) {
    return musics[musicIndex];
  }

  return musics[0];
}

Music getMusic(const String& key) {
  if (!mapInitialized) {
    initMusicMap();
  }

  if (musicMap.find(key) != musicMap.end()) {
    int index = musicMap[key];
    return musics[index];
  }

  return musics[0];
}
